name: pock_push_notification
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.1 
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^13.0.0  



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true

